Atas
fga-eps-mds/2023-1-Schedula-Doc pull request #1
Opened 2023-04-19 19:45 UTC by italovinicius18

2023-04-19 19:47 UTC, guilhermemoraisr submitted a review, later dismissed

2023-04-19 20:09 UTC, guilhermemoraisr commented on docs/atas/17_04_23.md
> +# Reunião 3 - 17/04/2023 - Lean - Brainsotorming de funcionalidades
Corrigir Brainsotorming para Brainstorming

2023-04-19 20:09 UTC, guilhermemoraisr commented on docs/atas/17_04_23.md
> +O grupo percorreu todo o novo Lean Inception e debateu em relação a última reunião que tivemos com os clientes, desenvolvemos e modificamos até a parte de brainstorm de funcionalidades.
Corrigir brainstorm para brainstorming

2023-04-26 20:02 UTC, AlvaroLeles requested changes

2023-04-26 21:07 UTC, merged