Adicionando página de planejamento de comunicação
fga-eps-mds/2023-1-Schedula-Doc pull request #64
Opened 2023-05-05 20:50 UTC by AlvaroLeles

Adicionando página de planejamento de comunicação

2023-05-05 21:10 UTC, italofernandes13 requested changes

2023-05-05 21:10 UTC, italofernandes13 commented on docs/planejamento/planejamento_comunicacao.md
> +|  <img src="../img/logo_github.png" width="100" style="border-radius: 50%" />  | Github | Repositórios de Documentação e código do projeto |
Recomendo colocar o "d" minúsculo em "Documentação"

2023-05-05 21:37 UTC, gabrielbpn approved these changes
Ok pra mim.

2023-05-08 22:31 UTC, italofernandes13 approved these changes

2023-05-08 22:33 UTC, merged